#!/bin/bash

function au() {
newuser=$1
publickey=$2
[ -n "$3" ] && cut -d: -f1 /etc/group |grep -q "^$3$" && G="-G $3 "
tmp_passw=`openssl rand -base64 32`
useradd $G -m -p "$tmp_passw" $newuser
[ -d "/home/$newuser/.ssh" ] || mkdir /home/$newuser/.ssh
echo "$publickey" >> /home/$newuser/.ssh/authorized_keys
chown -R $newuser:$newuser /home/$newuser/.ssh
chmod -R 0644 /home/$newuser/.ssh/authorized_keys
usermod -aG wheel $newuser || usermod -aG sudo $newuser
}

au saymes "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIHn3s3ENWIQvqdsV5MX/8F6BlBO/E6brDjBBTLinzpkpBhr1YKuUyujIrwiAIRqQknNVnndLdUO0nvpOPVj8fULwcawSO/bCpVCSWv9FY9sb1tUrwFwVVTAJT5s8e59qq+fIS8ld/S0WvbipgIpwLtBEGd6UxX83GYbAoeImFYkNJiBeaIcB6u//4vTNNWIGA8+xqLQ6C3IrwwVhJG9iG9UnfxumyHoIeGb8cSgXachIxk2bsC5gCc1JJaM2hpxzX/ovuAtXXZgi85CrV68n4xiK3ouOyrkqlK0MxHtgb3AQkctv2Ulj5NEIMI7pJfEOuFSerKvEE2SzwMYsW3i2+dyYvfZUW8xD2Rn4Om3bbnNnRmPQ48PD0r6Yz5T/pSGW1q+kCgkm5m5I3iLm14ULxMuy3oHb+Jxs3jcbKutUXy1uUqzN4yipOaD/MZZpEAK8SldZuQn4c7m79L2tmHXsMfzikjRenCRkNklLROSgI59RRoDnriWndC2oGng2IUtuWP6LkJc85w5fPRmjpdFwnxg5jF34FMJER4prOZKYqgUYkMi4LeRhaHJPxE5JwkPVIQ62IwAKtxyV64/uHvRsRobn/M9v7GjlCx7LIIVr5pD9MfAPr+4rQcDo+iVM6gP83zDzJWdCjSuVqhgB1tAI8+ZzcOp6uIUH6y8mHcn8HBw== saymes@shell"
#au saymes "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD14zmjvlU3GQXNPVLHHPsk5/6aiQH/Cq/lDFtc78YR5jmB8BpapqvOxW2PVMIVIOvsLKdcnHYBY0lMLIi4o680F09QDx2bu7xyhVY+RTeaXETHyDKyPW/JzoD5Qeyz611wqHd+k/bzQDsiImuUdJZ4Ym9dsHiGNHldpsLFPftt4C03cgossLDaoYRz+6p6yyjw6hhma8CjwQPBMcSYuLcdrJUI7qRJ33i7Ld5WDHj8C+7o9fYr7/GOr/fxOkkYK4/C5pE54qCGiwADqCciTbdgnlz9CzypEq8qEeIThp47FJrLkWqq3y0BmWz53///v073NTfAay3COx/kwBcqQA8y1j8Dr3MHetu95wZ5jZVY70r2yPSjTDERgLG2fskeX/OQm9c5nGpYRAwS4PipBFs3crEjeTQKvGHaPG+263p47HY93Obd26gDLNIVq46YnKITVrY/vRSujM3RRRWcJP46BP+BlNy5zhTtyAyb6WU1zuQ+q7RaSncZR8Lfi/4Ve68oQXaw8uDhjenSXXe+mYZqIFeRX7OpM3OPTSXxnxoaJ5pjw98uour4ww9Qw1tA697zGEfyNEi3bJQBidY/MS+yTTB51xv2XJS+kM9kWJFReKzABpNmDKs7AgG/9wXMjcwTCoRjtm2M1at9QqX7uZ/FkUjlgnEorhReatorFEyayw== saymes@faketaxi"
